CREATE TABLE gndr_main (
    time varchar(30),
    lat double,
    lon double,
    alt double,
    Current double,
    RSSI double,
    ECIO double,
    IO double,
    SINR double,
    RSRQ double,
    SNR double,
    RSRP double,
    s_pcid double,
    s_rc double,
    s_db double,
    s_lband varchar(30),
    s_State varchar(30),
    p_pcid double,
    p_rc double,
    p_db double,
    p_lband varchar(30)
);